name: stage_frontend

kind: pipeline      # https://docs.drone.io/pipeline/configuration/
type: docker

steps:

  - name: notify_about_start
    image: appleboy/drone-discord
    settings:
      webhook_id: 893421615042404383
      webhook_token: 64sAhkacw9k-eiDHh2ttp1aZ6Q1dN2UjNCOAGeyP2qV5YN8wuRxMlC7xDChPbzrRsiPG
      username: drone.io
      message: >
       ⚙️ [Build {{build.number}}](<{{ build.link }}/1/3>) of `{{repo.name}}`:`{{commit.branch}}` started.

       Latest [commit](<https://github.com/GoodBitDev/{{repo.name}}/commit/${DRONE_COMMIT_SHA:0:7}>) by {{commit.author}} on `{{commit.branch}}`:
       ```{{commit.message}}```
       [Image](<https://hub.docker.com/repository/docker/goodbitdev/builds>): `goodbitdev/builds:build-ec-client-stage-${DRONE_COMMIT_SHA:0:7}`
    when:
      event: [push]  # pull_request
      branch: [development]
      # event: tag # in case of new git tag added

  # or this can be done via drone.io docker plugin, not using list of commands
  - name: build_stage
    image: docker:latest
    environment:
      DOCKER_HUB_USERNAME:
        from_secret: DOCKER_HUB_USERNAME # from org secrets
      DOCKER_HUB_PASSWORD:
        from_secret: DOCKER_HUB_PASSWORD # from org secrets
      MAIN_CLIENT_IMAGE: goodbitdev/builds:build-ec-client-stage-${DRONE_COMMIT_SHA:0:7}
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - df -h
      - docker images  # for debug purpose
      - docker build --build-arg NODE_ENV=stage --build-arg BASE_URL=https://api.eatchefs.goodbit.dev --build-arg DOMAIN=eatchefs.goodbit.dev -t $MAIN_CLIENT_IMAGE .
      - echo $DOCKER_HUB_PASSWORD | docker login docker.io -u $DOCKER_HUB_USERNAME --password-stdin
      - echo $MAIN_CLIENT_IMAGE
      - docker push $MAIN_CLIENT_IMAGE
      - docker container prune --force --filter "until=36h"
      - docker image prune -a --force --filter "until=36h"
    when:
      event: [push]
      branch: [development]
      # event: tag # in case of new git tag

  - name: notify_after_build_stage
    image: appleboy/drone-discord
    settings:
      webhook_id: 893421615042404383
      webhook_token: 64sAhkacw9k-eiDHh2ttp1aZ6Q1dN2UjNCOAGeyP2qV5YN8wuRxMlC7xDChPbzrRsiPG
      username: drone.io
      message: >
       {{#success build.status}}
         ✅ Build {{build.number}} of '{{repo.name}}':{{commit.branch}}. Status: OK.
       {{else}}
         ❌ Build {{build.number}} of '{{repo.name}}'. Status: FAIL.
       {{/success}}
    when:
      event: [push]  # pull_request
      branch: [development]
      # event: tag # in case of new git tag
      status:
      - success
      - failure

  - name: deploy_stage
    image: appleboy/drone-ssh
    environment:
      DOCKER_HUB_USERNAME:
        from_secret: DOCKER_HUB_USERNAME # from org secrets
      DOCKER_HUB_PASSWORD:
        from_secret: DOCKER_HUB_PASSWORD # from org secrets
    settings:
      host: eatchefs.goodbit.dev
      username: nitsenko94
      key:
          from_secret: SSH_PRIVATE_KEY  # from org secrets
      port: 22
      envs: [DOCKER_HUB_USERNAME, DOCKER_HUB_PASSWORD]
      script:
        # - whoami
        - echo $DOCKER_HUB_PASSWORD | docker login docker.io -u $DOCKER_HUB_USERNAME --password-stdin
        # test: - docker pull goodbitdev/builds:build-ec-client-stage-004abf9
        - cd /home/nitsenko94/services/eatchef_client/ci/stage
        - python3 scripts.py deploy goodbitdev/builds:build-ec-client-stage-${DRONE_COMMIT_SHA:0:7}
        - docker image prune -a --force --filter "until=72h"  # 3 days
    when:
      event: [push]  # pull_request
      branch: [development]
      # event: tag # in case of new git tag
      status:
      - success

  - name: notify_after_deploy_stage
    image: appleboy/drone-discord
    settings:
      webhook_id: 893421615042404383
      webhook_token: 64sAhkacw9k-eiDHh2ttp1aZ6Q1dN2UjNCOAGeyP2qV5YN8wuRxMlC7xDChPbzrRsiPG
      username: drone.io
      message: >
       {{#success build.status}}
         ✅ Deploy of [build {{build.number}}](<{{ build.link }}/1/3>) to stage-1 [eatchefs.goodbit.dev](<https://eatchefs.goodbit.dev/>). Status: OK.
       {{else}}
         ❌ Deploy of [build {{build.number}}](<{{ build.link }}/1/3>) to stage-1 [eatchefs.goodbit.dev](<https://eatchefs.goodbit.dev/>). Status: FAIL.
       {{/success}}
    when:
      event: [push]  # pull_request
      branch: [development]
      # event: tag # in case of new git tag
      status:
      - success
      - failure

# TEST

  - name: build_test
    image: docker:latest
    environment:
      DOCKER_HUB_USERNAME:
        from_secret: DOCKER_HUB_USERNAME # from org secrets
      DOCKER_HUB_PASSWORD:
        from_secret: DOCKER_HUB_PASSWORD # from org secrets
      MAIN_CLIENT_IMAGE: goodbitdev/builds:build-ec-client-test-${DRONE_COMMIT_SHA:0:7}
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - df -h
      - docker images  # for debug purpose
      - docker build --build-arg NODE_ENV=stage --build-arg BASE_URL=https://api.test.eatchefs.com --build-arg DOMAIN=test.eatchefs.com -t $MAIN_CLIENT_IMAGE .
      - echo $DOCKER_HUB_PASSWORD | docker login docker.io -u $DOCKER_HUB_USERNAME --password-stdin
      - echo $MAIN_CLIENT_IMAGE
      - docker push $MAIN_CLIENT_IMAGE
      - docker container prune --force --filter "until=36h"
      - docker image prune -a --force --filter "until=36h"
    when:
      event: [push]
      branch: [development]
      # event: tag # in case of new git tag

  - name: notify_after_build_test
    image: appleboy/drone-discord
    settings:
      webhook_id: 893421615042404383
      webhook_token: 64sAhkacw9k-eiDHh2ttp1aZ6Q1dN2UjNCOAGeyP2qV5YN8wuRxMlC7xDChPbzrRsiPG
      username: drone.io
      message: >
       {{#success build.status}}
         ✅ Build {{build.number}} of '{{repo.name}}':{{commit.branch}}. Status: OK.
       {{else}}
         ❌ Build {{build.number}} of '{{repo.name}}'. Status: FAIL.
       {{/success}}
    when:
      event: [push]  # pull_request
      branch: [development]
      # event: tag # in case of new git tag
      status:
      - success
      - failure

  - name: deploy_test
    image: appleboy/drone-ssh
    environment:
      DOCKER_HUB_USERNAME:
        from_secret: DOCKER_HUB_USERNAME # from org secrets
      DOCKER_HUB_PASSWORD:
        from_secret: DOCKER_HUB_PASSWORD # from org secrets
    settings:
      host: test.eatchefs.com
      username: nitsenko94
      key:
          from_secret: SSH_PRIVATE_KEY  # from org secrets
      port: 22
      envs: [DOCKER_HUB_USERNAME, DOCKER_HUB_PASSWORD]
      script:
        # - whoami
        - echo $DOCKER_HUB_PASSWORD | docker login docker.io -u $DOCKER_HUB_USERNAME --password-stdin
        - cd /home/nitsenko94/services/eatchef_client/ci/stage
        - python3 scripts.py deploy goodbitdev/builds:build-ec-client-test-${DRONE_COMMIT_SHA:0:7}
        - docker image prune -a --force --filter "until=72h"  # 3 days
    when:
      event: [push]  # pull_request
      branch: [development]
      # event: tag # in case of new git tag
      status:
      - success

  - name: notify_after_deploy_test
    image: appleboy/drone-discord
    settings:
      webhook_id: 893421615042404383
      webhook_token: 64sAhkacw9k-eiDHh2ttp1aZ6Q1dN2UjNCOAGeyP2qV5YN8wuRxMlC7xDChPbzrRsiPG
      username: drone.io
      message: >
       {{#success build.status}}
         ✅ Deploy of [build {{build.number}}](<{{ build.link }}/1/3>) to test [test.eatchefs.com](<https://test.eatchefs.com/>). Status: OK.
       {{else}}
         ❌ Deploy of [build {{build.number}}](<{{ build.link }}/1/3>) to test [test.eatchefs.com](<https://test.eatchefs.com/>). Status: FAIL.
       {{/success}}
    when:
      event: [push]  # pull_request
      branch: [development]
      # event: tag # in case of new git tag
      status:
      - success
      - failure

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

